### ISSUE TITLE
 DataLoader worker (pid 13176) is killed by signal: Bus error

### ISSUE THREAD

**Issue by meta-tabchen** [liqunhit/NeuralClassifier#3]
![image](https://user-images.githubusercontent.com/19347690/59681111-b1fab480-9205-11e9-84ce-85a871a3d918.png)

![image](https://user-images.githubusercontent.com/19347690/59681139-c50d8480-9205-11e9-8552-f1a0637fbae9.png)

**Comment by liqunhit** [comment]
insufficient memory problem, check your machine memory...
