### ISSUE TITLE
Why no FastText in Encoder?

### ISSUE THREAD

**Issue by LMY-nlp0701** [liqunhit/NeuralClassifier#4]
Hello! author.
Thank you very much for your open source project.

I find that you have achieved FastText.
1. In code: [https://github.com/liqunhit/NeuralClassifier/blob/master/model/classification/fasttext.py](url)
2. In configuration picture:
[https://github.com/liqunhit/NeuralClassifier/blob/master/readme/deeptext_arc.pnghttps://github.com/liqunhit/NeuralClassifier/blob/master/readme/deeptext_arc.png](url)

However, the configuration of FastText does not appear in the "conf/train.json" file.
So there are the following problems in direct running.
![image](https://user-images.githubusercontent.com/33420219/59973210-02d82780-95cf-11e9-8861-332ef6528c4e.png)

Thank you for answering my question!

**Comment by liqunhit** [comment]
"model_name": "FastText"
It is ok.
You can provide a complete "train.conf" to help you see why.

Best,
Liqun


lmy_nlp <notifications@github.com> 于2019年6月23日周日 下午4:25写道：
